### ISSUE TITLE
No CORS when receiving a 400 Bad Request response

### ISSUE THREAD

**Issue by JohanDufau** [CovidJournal/backend#2]
For instance, when you do a mistake in the request payload:

POST {{BASE_URL}}/login
Body:
{
	"email": "contact@creatiwity.net",
	"role": "Pro",
	"organizationName": null
}

We get a 400 - Bad request (which is good) but without CORS whereas it is correctly configured in warp. We need to check what is going on there.

**Comment by julien1619** [comment]
I think the recover method does not handle all error cases, it goes to the default handler which is not covered yet by the cors middleware. I'll check if we can add cors first in the filtering to avoid any strange case like this.
